### ISSUE TITLE
Footer page color pallet not fully showing

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/supreme#7]
If we to change the color on the following elements on the footer, we will not see the full color pallet :
Footer Widget Title Color : https://prnt.sc/v4glcs
Footer Anchor Color : https://prnt.sc/v4glkb
Footer Anchor Hover Color: https://prnt.sc/v4glzf

**Comment by mahendrapratap4022** [comment]
Hi, It's the epsilon-framework issue I have created the issue here https://github.com/WPChill/epsilon-framework/issues/197 and also created the PR with the fix https://github.com/WPChill/epsilon-framework/pull/198  hope they approve and merge it soon.
Thanks
